# Only test master and pull requests; skip tags.
# Other branches can allow themselves.
branches:
  only:
    - pypostgresql

# Prefer docker container with setuid/sudo
sudo: required

language: python

python:
  - "3.6"

cache: pip

addons:
  postgresql: "9.4"

env:
  - TOXENV=py34-pypostgresql

matrix:
  fast_finish: true

install: travis_retry pip install tox ppu

script: tox -e ${TOXENV}

before_cache:
  - remove-old-files.py -o 180 ~/.cache/pip
