# Install SQLObject on windows and test against MS SQL server and postgres
# Heavily inspired by Oliver Grisel's appveyor-demo (https://github.com/ogrisel/python-appveyor-demo)
# and Michael Sverdlik's appveyor-utils (https://github.com/cloudify-cosmo/appveyor-utils)
version: '{branch}-{build}'

# Only test master and pull requests; skip tags.
# Other branches can allow themselves.
branches:
  only:
    - pypostgresql
skip_branch_with_pr: false
skip_tags: true

cache:
  - '%LOCALAPPDATA%\pip\Cache'

# Match travis
clone_depth: 50

services:
  - postgresql

environment:
  PGUSER: "postgres"
  PGPASSWORD: "Password12!"

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\run_with_env.cmd"

  matrix:
    - TOX_ENV: "py34-pypostgresql-w32"
      PYTHON_ARCH: "32"
      PYTHON_VERSION: "3.4"
      PYTHON_HOME: "C:\\Python34"
      db: postgresql
    - TOX_ENV: "py34-pypostgresql-w32"
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "3.4"
      PYTHON_HOME: "C:\\Python34-x64"
      db: postgresql

install:
  # Ensure we use the right python version
  - "SET PATH=%PYTHON_HOME%;%PYTHON_HOME%\\Scripts;C:\\Program Files\\MySQL\\MySQL Server 5.7\\bin;C:\\Program Files\\PostgreSQL\\9.5\\bin;%PATH%"
  - "SET TOXPYTHON=%PYTHON_HOME%\\python.exe"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip --version"
  - "pip install tox ppu"

# Not a C project, so no build step
build: false

test_script:
  - "%CMD_IN_ENV% tox -e %TOX_ENV%"

after_test:
  - "remove-old-files.py -o 180 %LOCALAPPDATA%\\pip\\Cache"
